sudo: required
language: go

go:
- 1.11.x

services:
- docker

addons:
  apt:
    packages:
    - docker-ce

script:
- set -e
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure -vendor-only
- go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...
- docker build -t kubesec .
- docker run -dp 9090:9090 kubesec

after_success:
- set -e
- sleep 1
- curl -sSX POST --data-binary @test/asset/score-0-daemonset-host-network.yml http://localhost:9090/scan

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
